FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir snscrape kafka-python

COPY . .

CMD ["python", "secure/osin/ingestion/twitter/multi_strategy.py"]
