apiVersion: v1
kind: Secret
metadata:
  name: reddit-api-secrets
  namespace: osin-production
type: Opaque
data:
  client-id: <base64-encoded-client-id>
  client-secret: <base64-encoded-client-secret>
  username: <base64-encoded-username>
  password: <base64-encoded-password>
