apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: osin-system
type: Opaque
stringData:
  root-user: "osin_admin"
  root-password: "osin_secure_password_2026"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: osin-system
type: Opaque
stringData:
  password: "postgres_osin_secure"
