apiVersion: v1
kind: Secret
metadata:
  name: twitter-api-secrets
  namespace: osin-production
type: Opaque
data:
  twitter-bearer-token: <base64-encoded-token>
  twitter-consumer-key: <base64-encoded-key>
  twitter-consumer-secret: <base64-encoded-secret>
