# RTKLIB configuration file - OSIN Precision Standard
pos1-posmode       =kinematic  # positioning mode (0:single,1:dgps,2:kinematic,3:static)
pos1-frequency     =l1+l2+l5   # frequency (1:l1,2:l1+l2,3:l1+l2+l5)
pos1-soltype       =forward    # solution type (0:forward,1:backward)
pos1-elmask        =15         # elevation mask (deg)
pos1-snrmask       =0          # SNR mask (dBHz)
pos1-dynamics      =on         # dynamics model (0:off,1:on)
pos1-ionoopt       =brdc       # ionosphere option (1:brdc,2:sbas)
pos1-tropopt       =saas       # troposphere option (1:saas,2:sbas)
pos2-armode        =fix-and-hold  # AR mode (3:fix-and-hold)
pos2-gloarmode     =on
pos2-arthres       =3
out-solformat      =llh        # solution format (0:llh)
out-timesys        =gpst       # time system (0:gpst)
out-degform        =deg        # lat/lon format (0:deg)
out-height         =ellipsoidal
